name: actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: ['make', 'cmake']

    steps:
    - uses: actions/checkout@v3
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11

    - name: Compile using make
      if: matrix.compiler == 'make'
      run: |
        make
      shell: bash

    - name: Compile using cmake
      if: matrix.compiler == 'cmake'
      run: |
        cmake ./ && cmake --build ./
      shell: bash

    - name: Run
      run: |
          cd example
          ../packmol < water_box.inp
          cd ..
      shell: bash
